---
title: "data_manipulation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Import FAS csv files

import my first csv

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv", col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)
pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

## Select variables
```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```
```{r}
select(litters_data, group:gd_of_birth)
```
...by saying what you want to remove
```{r}
select(litters_data, -pups_survive)
```
...and rename
```{r}
select(litters_data, group, litter_number, gest_day_0_weight = gd0_weight)
rename(litters_data, gest_day_0_weight = gd0_weight)
```
,,,use select helpers???
```{r}
select(litters_data, litter_number, starts_with("pup"))
select(litters_data, litter_number, everything())
```
litter number, sex, and PD ears
```{r}
select(pups_data, litter_number, sex, pd_ears)
```

## Filter
```{r}
filter(litters_data, gd0_weight < 25)
filter(litters_data, gd0_weight >= 25)
filter(litters_data, is.na(gd0_weight))
filter(litters_data, group %in% c("Con7", "Con8"))
```
```{r}
filter(pups_data, sex == 1)
filter(pups_data, pd_walk < 11, sex == 2)
```

## Mutate
```{r}
mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       group = tolower(group)
       )
mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       wt_gain_squared = wt_gain^2
       )
```


## Arrange

Arrange the data
```{r}
arrange(litters_data, desc(pups_born_alive))
```

## Piping
```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = mutate(litters_data_selected_cols, 
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group))
litters_data_with_vars
```

```{r}
litters_data_clean = 
  mutate(
    select(
      janitor::clean_names(
        read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
        ), 
    -pups_survive
    ),
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group)
  )
litters_data_clean
```

Use piping
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group)) %>%
filter(!is.na(gd0_weight)) 
litters_data
```

illustrate placeholder use with `lm`
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group)) %>%
  filter(!is.na(gd0_weight)) %>% 
  lm(formula = gd18_weight ~ gd0_weight, data = .)
  
```

practice

```{r}
read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>% 
  filter(sex == 1) %>% 
  select(-pd_ears) %>% 
  mutate(pd_pivot_gt7 = pd_pivot > 7)
```

