---
title: "data_wrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
library(tidyverse)
```

# Import FAS csv files

import my first csv

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

```

import the pups data also
```{r}
pups_data = read_csv("./data/FAS_pups.csv")
```

##look at data

```{r}
head(litters_data)
tail(litters_data)
skimr::skim(litters_data)
```

skip some rows
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv", col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
skimr::skim(pups_data)

```

Read in mlb data
```{r}
mlb11_data = readxl::read_excel("./data/mlb11.xlsx")
head(mlb11_data, 5)
mlb11_subset = readxl::read_excel(path = "./data/mlb11.xlsx", range = "A1:E17")
```

Read in pulse data


## Compare with base R

```{r}
pups_base = read.csv("./data/FAS_pups.csv")
pups_readr = read_csv("./data/FAS_pups.csv")

pups_base
pups_readr

pups_base$S
pups_readr$Sex
```


